name: .NET Core

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest   
    env:
      build_dir:  ./src/Dotnet.Spark.Examples/
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
      
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{ env.build_dir }}
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{ env.build_dir }}
   
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ${{ env.build_dir }}
